app/urls.py
from django.conf.urls import url

from app import views

urlpatterns=[
    url(r'^base/$', views.base, name='base'),
    url(r'^home/$', views.home, name='home'),
    url(r'^market/$', views.market, name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$', views.market, name='market'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^mine/$', views.mine, name='mine'),

    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    # 检测注册——ajax
    url(r'^check_01/$', views.check_01, name='check_01'),
    url(r'^check_02/$', views.check_02, name='check_02'),
    url(r'^check_03/$', views.check_03, name='check_03'),
    # url(r'^check_04/$', views.check_04, name='check_04'),

    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^minuscart/$', views.minuscart, name='minuscart'),
    url(r'^changestatus/$',views.changestatus,name='changestatus'),
    url(r'^changeall/$',views.changeall,name='changeall'),

    # 订单操作
    # 生成订单
    url(r'^generateorder/$', views.generateorder, name='generateorder'),
]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls',namespace='app')),
]

app/models.py
from django.db import models

# Create your models here.
class Lunbo(models.Model):
    # img,name,trackid
    img=models.CharField(max_length=100)
    name=models.CharField(max_length=100)
    trackid=models.CharField(max_length=100)

    class Meta:
        db_table='axf_wheel'

class Nav(models.Model):
    # img, name, trackid
    img=models.CharField(max_length=100)
    name=models.CharField(max_length=100)
    trackid=models.CharField(max_length=100)

    class Meta:
        db_table='axf_nav'

class Mustbuy(models.Model):
    img=models.CharField(max_length=100)
    name=models.CharField(max_length=100)
    trackid=models.CharField(max_length=100)

    class Meta:
        db_table='axf_mustbuy'

class Shop(models.Model):
    img=models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    trackid = models.CharField(max_length=100)

    class Meta:
        db_table='axf_shop'

class Mainshow(models.Model):
    # trackid, name, img, categoryid, brandname, \
    # img1, childcid1, productid1, longname1, price1, marketprice1, \
    # img2, childcid2, productid2, longname2, price2, marketprice2, \
    # img3, childcid3, productid3, longname3, price3, marketprice3
    trackid=models.CharField(max_length=100)
    name=models.CharField(max_length=100)
    img= models.CharField(max_length=100)
    categoryid= models.CharField(max_length=100)
    brandname = models.CharField(max_length=100)

    img1= models.CharField(max_length=100)
    childcid1= models.CharField(max_length=100)
    productid1= models.CharField(max_length=100)
    longname1= models.CharField(max_length=100)
    price1= models.CharField(max_length=100)
    marketprice1= models.CharField(max_length=100)

    img2 = models.CharField(max_length=100)
    childcid2 = models.CharField(max_length=100)
    productid2 = models.CharField(max_length=100)
    longname2 = models.CharField(max_length=100)
    price2 = models.CharField(max_length=100)
    marketprice2 = models.CharField(max_length=100)

    img3 = models.CharField(max_length=100)
    childcid3 = models.CharField(max_length=100)
    productid3 = models.CharField(max_length=100)
    longname3 = models.CharField(max_length=100)
    price3 = models.CharField(max_length=100)
    marketprice3 = models.CharField(max_length=100)

    class Meta:
        db_table='axf_mainshow'


class Foodtypes(models.Model):
    # typeid, typename, childtypenames, typesort
    typeid=models.CharField(max_length=100)
    typename=models.CharField(max_length=100)
    childtypenames=models.CharField(max_length=300)
    typesort=models.IntegerField()

    class Meta:
        db_table='axf_foodtypes'

class Goods(models.Model):
    # productid, productimg, productname, productlongname,
    # isxf, pmdesc, specifics, price, marketprice,
    # categoryid, childcid,
    # childcidname, dealerid, storenums, productnum

    productid=models.CharField(max_length=100)
    productimg=models.CharField(max_length=300)
    productname=models.CharField(max_length=100)
    productlongname=models.CharField(max_length=200)
    isxf=models.IntegerField(default=0)
    pmdesc=models.IntegerField(default=0)
    specifics=models.CharField(max_length=100)

    price=models.DecimalField(max_digits=8,decimal_places=2)

    marketprice=models.DecimalField(max_digits=8,decimal_places=2)

    categoryid=models.IntegerField()

    childcid=models.IntegerField()

    childcidname=models.CharField(max_length=100)

    dealerid=models.CharField(max_length=100)

    storenums=models.IntegerField()

    productnum=models.IntegerField()

    class Meta:
        db_table='axf_goods'

class User(models.Model):
    username=models.CharField(max_length=100,unique=True)
    password=models.CharField(max_length=300)
    name=models.CharField(max_length=100)

    class Meta:
        db_table='注册用户信息'

# 购物车模型类
class Cart(models.Model):
    # 用户(属于哪个用户)
    user=models.ForeignKey(User)
    #商品(添加哪个商品）
    goods = models.ForeignKey(Goods)

    # 具体规格
    number=models.IntegerField()

    isselect=models.BooleanField(default=True)

    isdelete=models.BooleanField(default=False)

    class Meta:
        db_table='爱鲜蜂——购物车'


# 订单类模型
class Order(models.Model):
    user=models.ForeignKey(User)
    # 创建时间
    createtime=models.DateTimeField(auto_now_add=True)
    # 更新时间
    updatetime=models.DateTimeField(auto_now=True)

    # 状态：-1 过期  0未付款  1已付款，待发货  2已发货，待收货  3已收货，待评价
    status=models.IntegerField(default=0)
    # 订单号
    identifier=models.CharField(max_length=300)

class OrderGoods(models.Model):
    order=models.ForeignKey(Order)

    goods=models.ForeignKey(Goods)

    number=models.IntegerField()

templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}


{% block title %}
    <title>购物车</title>
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css'%}">
{% endblock %}

{% block content %}



            <div class="cart">
                <ul>
                    {% for cart in carts %}
                        <li>
                        <div class="confirm-wrapper" cartid="{{ cart.id }}">
                            {% if cart.isselect %}
                                <span class="glyphicon glyphicon-ok"></span>
                            {% else %}
                                <span class="no"></span>
                            {% endif %}
                        </div>

                        <div class="content-wrapper">
                            <div class="img">
                                <img src="{{ cart.goods.productimg }}">
                            </div>
                            <div class="detail">
                                <p class="name" name="{{ cart.goods.productlongname }}">{{ cart.goods.productlongname }}</p>
                                <p class="price" price="{{ cart.goods.price }}">{{ cart.goods.price }}</p>
                                <p class="num" num="{{ cart.number }}">x{{ cart.number }}</p>
                            </div>
                        </div>
                    </li>
                    {% endfor %}


                </ul>
                <div class="bill">
                    <div class="bill-left">
                        <div class="all" isall="{{ isall }}">
                            {% if isall %}
                                <span class="glyphicon glyphicon-ok"></span>
                                <b>全选</b>
                            {% else %}
                                <span class="no"></span>
                                <b>全选</b>
                            {% endif %}

                        </div>
                        <div class="total">
                            <span>$</span>
                            <b>0</b>
                        </div>
                    </div>

                    <div class="bill-right">
                        <a href="{% url 'app:generateorder' %}">下单</a>
                    </div>
                </div>
            </div>



{% endblock %}




{% block extjs %}
    <script src="{% static 'cart/js/cart.js'%}"></script>
{% endblock %}

templates/cart/orderdetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>订单详情</title>
</head>
<body>
    <div>订单号：{{ order.identifier }}</div>
    {% for ordergoods in order.ordergoods_set.all %}
        <div>

            <span>{{ ordergoods.goods.productlongname }}</span>
            <span>X{{ ordergoods.number }}</span>

        </div>
    {% endfor %}
    <button>支付</button>
</body>
</html>