app/urls.py
from django.conf.urls import url

from app import views

urlpatterns=[
    url(r'^base/$', views.base, name='base'),
    url(r'^home/$', views.home, name='home'),
    url(r'^market/$', views.market, name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$', views.market, name='market'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^mine/$', views.mine, name='mine'),

    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    # 检测注册——ajax
    url(r'^check_01/$', views.check_01, name='check_01'),
    url(r'^check_02/$', views.check_02, name='check_02'),
    url(r'^check_03/$', views.check_03, name='check_03'),
    # url(r'^check_04/$', views.check_04, name='check_04'),

    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^minuscart/$', views.minuscart, name='minuscart'),
    url(r'^changestatus/$',views.changestatus,name='changestatus'),
    url(r'^changeall/$',views.changeall,name='changeall'),

    # 订单操作
    # 生成订单
    url(r'^generateorder/$', views.generateorder, name='generateorder'),
]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls',namespace='app')),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>Base</title>
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">



    {% block extcss %}axf_foodtypes

    {% endblock %}

</head>
<body>
{% block body %}

    {% block header %}
        <header>爱鲜蜂</header>
    {% endblock %}
<div class="hidescroll">
    {% block content %}

            <div id="content">主页</div>

    {% endblock %}
</div>
    {% block footer %}
        <footer>
            <a href="{% url 'app:home' %}" class="home">
                <dl>
                    <dt><span></span></dt>
                    <dd>首页</dd>
                </dl>
            </a>
            <a href="{% url 'app:marketbase' %}" class="market">
                <dl>
                    <dt><span></span></dt>
                    <dd>闪购超市</dd>
                </dl>
            </a>
            <a href="{% url 'app:cart' %}" class="cart">
                <dl>
                    <dt><span></span></dt>
                    <dd>购物车</dd>
                </dl>
            </a>
            <a href="{% url 'app:mine' %}" class="mine">
                <dl>
                    <dt><span></span></dt>
                    <dd>我的</dd>
                </dl>
            </a>
        </footer>
    {% endblock %}





{% endblock %}
<script src="{% static 'base/js/jquery.min.js' %}"></script>
<script src="{% static 'base/js/jquery.cookie.js' %}"></script>
<script src="{% static 'base/js/base.js' %}"></script>
<script src="{% static 'base/js/bootstrap.js' %}"></script>


{% block extjs %}

{% endblock %}
</body>
</html>