app/urls.py
from django.conf.urls import url

from app import views

urlpatterns=[
    url(r'^base/$', views.base, name='base'),
    url(r'^home/$', views.home, name='home'),
    url(r'^market/$', views.market, name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$', views.market, name='market'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^mine/$', views.mine, name='mine'),

    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    # 检测注册——ajax
    url(r'^check_01/$', views.check_01, name='check_01'),
    url(r'^check_02/$', views.check_02, name='check_02'),
    url(r'^check_03/$', views.check_03, name='check_03'),
    # url(r'^check_04/$', views.check_04, name='check_04'),

    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^minuscart/$', views.minuscart, name='minuscart'),
    url(r'^changestatus/$',views.changestatus,name='changestatus'),
    url(r'^changeall/$',views.changeall,name='changeall'),

    # 订单操作
    # 生成订单
    url(r'^generateorder/$', views.generateorder, name='generateorder'),
]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls',namespace='app')),
]

templates/market/market.html
{% extends 'base/base.html' %}
{% load static %}


{% block title %}
    <title>闪购超市</title>
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'market/css/market.css' %}">
{% endblock %}

{% block content %}

    <div id="content">

        <div class="market">
            {#            分类#}
            <div class="type-slider">
                <ul>
                    {% for foodtype in foodtypes %}
                        <li>

                            <a href="{% url 'app:marketbase'%}">
                                <span></span>

                                {{ foodtype.typename }}


                            </a>


                        </li>
                    {% endfor %}


                </ul>
            </div>
            {#                导航#}
            <nav>
                <ul>
                    <li>
                            <span id="category_bt">

                                    全部类型
                                <i class="glyphicon glyphicon-chevron-up"></i>
                            </span>
                    </li>
                    <li>
                            <span id="sort_bt">

                                  综合排序
                                <i class="glyphicon glyphicon-chevron-up"></i>
                            </span>
                    </li>
                </ul>
            </nav>

            <div class="main-content">
                <div class="content-wrapper">
                    <ul>
                        {% for good in goods %}
                            <li>
                                <a href="#" class="container">
                                    <img class="goods-img" src="{{ good.productimg }}">
                                    <div class="goods-info">
                                        <div class="name">{{ good.productlongname }}</div>
                                        <div class="detailtag">
                                            {% if good.isxf %}
                                                <div class="xf">精选</div>
                                            {% endif %}

                                            <i></i>
                                        </div>
                                        <div class="specifics">{{ good.specifics }}</div>
                                        <div class="price">

                                            <span class="now-price">{{ good.price }}</span>
                                            <span class="market-price">{{ good.marketprice }}</span>

                                        </div>
                                    </div>
                                </a>
                                <div class="bt-wrapper">
                                    <span class="glyphicon glyphicon-minus" goodid="{{ good.id }}"></span>
                                    <span class="num"></span>
                                    <span class="glyphicon glyphicon-plus" goodid="{{ good.id }}"></span>
                                </div>
                            </li>
                        {% endfor %}


                    </ul>
                </div>
                <div class="bounce-view category_view">
                    {% for child_list in child_lists %}
                        <span class="bounce-wrapper">
                            <a href="{% url 'app:market' child_list.id 0%}">{{ child_list.name }}</a>
                        </span>
                    {% endfor %}


                </div>
                <div class="bounce-view sort_view">

                        <span class="bounce-wrapper">
                            <a href="{% url 'app:market' childid 0%}">综合排序</a>
                            <a href="{% url 'app:market' childid 1%}">销量排序</a>
                            <a href="{% url 'app:market' childid 2%}">价格最低</a>
                            <a href="{% url 'app:market' childid 3%}">价格最高</a>
                        </span>



                </div>
            </div>
        </div>


    </div>

{% endblock %}




{% block extjs %}
    <script src="{% static 'market/js/market.js' %}"></script>
{% endblock %}