app/urls.py
from django.conf.urls import url

from app import views

urlpatterns=[
    url(r'^base/$', views.base, name='base'),
    url(r'^home/$', views.home, name='home'),
    url(r'^market/$', views.market, name='marketbase'),
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$', views.market, name='market'),
    url(r'^cart/$', views.cart, name='cart'),
    url(r'^mine/$', views.mine, name='mine'),

    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
    # 检测注册——ajax
    url(r'^check_01/$', views.check_01, name='check_01'),
    url(r'^check_02/$', views.check_02, name='check_02'),
    url(r'^check_03/$', views.check_03, name='check_03'),
    # url(r'^check_04/$', views.check_04, name='check_04'),

    url(r'^addcart/$', views.addcart, name='addcart'),
    url(r'^minuscart/$', views.minuscart, name='minuscart'),
    url(r'^changestatus/$',views.changestatus,name='changestatus'),
    url(r'^changeall/$',views.changeall,name='changeall'),

    # 订单操作
    # 生成订单
    url(r'^generateorder/$', views.generateorder, name='generateorder'),
]

axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('app.urls',namespace='app')),
]

templates/mine/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block footer %}
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/jquery-1.12.3.js' %}"></script>
    <script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="login">
        <div class="back">
            <a href="{% url 'app:mine' %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>
               <form class="form-inline" action="{% url 'app:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group input-group">

                <div class="input-group">
                    <div class="input-group-addon" id="username">账户</div>
                    <input type="text" class="form-control" id="exampleInputAmount" placeholder="用户登录邮箱" name="username">
                    <p id="error_username"></p>

                </div>
                <div class="input-group">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" id="exampleInputAmount" placeholder="用户登录密码" name="password">
                </div>
            </div>
            <div><span id="user_error" style="color: red">{{ error }}</span></div>
            <input type="submit" class="btn btn-primary" value="登录" style="width: 80%" id="subButton">
        </form>



    </div>
{% endblock %}

templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}


{% block title %}
    <title>我的</title>
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}


{% block content %}

    <div id="content">
        <div class="mine">
            <div class="user-wrapper">
                <div class="user-img">
                    <img src="{% static 'mine/img/222.jpg' %}">
                </div>
                <div class="user-content">
                    {% if token %}
                        <p><span class="glyphicon glyphicon-user"></span>{{ user.name }}</p>
                        <p><span class="glyphicon glyphicon-star"></span>等级 Level 1</p>
                        <div class="register">
                        <a href="{% url 'app:logout' %}" style="list-style: none;color: white">注销</a>
                    </div>
                    {% else %}
                        <p><span class="glyphicon glyphicon-user"></span><a href="{% url 'app:login' %}">未登录</a></p>
                        <p><span class="glyphicon glyphicon-star"></span>等级无</p>
                        <div class="register">
                        <a href="{% url 'app:register' %}" style="list-style: none;color: white">注册</a>
                    </div>
                    {% endif %}


                </div>
            </div>
            <div class="collect">

                <div class="glyphicon glyphicon-heart">
                    <span>商品收藏</span>
                </div>


            </div>
            <div class="other">
                <section class="my">

                    <span>我的订单</span>
                    <a>查看全部订单</a>

                </section>
                <section>
                    <ul>
                        <li>
                            <dl>
                                <dt class="glyphicon glyphicon-gift"></dt>
                                <dd>待付款</dd>
                            </dl>
                        </li>
                        <li>
                            <dl>
                                <dt class="glyphicon glyphicon-leaf"></dt>
                                <dd>待收货</dd>
                            </dl>
                        </li>
                        <li>
                            <dl>
                                <dt class="glyphicon glyphicon-plane"></dt>
                                <dd>待评价</dd>
                            </dl>
                        </li>
                        <li>
                            <dl>
                                <dt class="glyphicon glyphicon-thumbs-up"></dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </li>
                    </ul>
                </section>
                <section>
                    <ul>
                        <li>
                            <dl>
                                <dt class="glyphicon glyphicon-book"></dt>
                                <dd>优惠券</dd>
                            </dl>
                        </li>
                        <li>
                            <dl>
                                <dt class="glyphicon glyphicon-adjus"></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </li>
                        <li>
                            <dl>
                                <dt class="glyphicon glyphicon-link"></dt>
                                <dd>客户反馈</dd>
                            </dl>
                        </li>
                        <li>
                            <dl>
                                <dt class="glyphicon glyphicon-save"></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </li>
                </section>
                <section style="background-color: greenyellow">
                    {% if token %}
                        <div class="quit">
                            <a href="{% url 'app:logout' %}">退出登录</a>
                        </div>
                    {% else %}
                        <div class="quit">
                            <a href="#">登录</a>
                        </div>
                    {% endif %}

                </section>

            </div>
        </div>
    </div>

{% endblock %}



{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

templates/mine/register.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    <title>注册界面</title>
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/register.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/jquery-1.12.3.js' %}"></script>
    <script src="{% static 'mine/js/register.js' %}"></script>

{% endblock %}

{% block footer %}
{% endblock %}

{% block content %}
    <div class="register">
        <div class="back">
            <a href="{% url 'app:mine' %}">
                <span class="glyphicon glyphicon-remove"></span>
            </a>
        </div>

        <form class="form-inline" action="{% url 'app:register' %}" method="post">
            {% csrf_token %}
            <div class="form-group input-group">

{#           正确标注，父类标签要带 form-group has-success has-feedback，要有打钩，得添加span标签（含特别标注的）class="glyphicon glyphicon-ok form-control-feedback"    #}
{#                错误标注，父类标签要带has-error has-feedback，带打错，得添加span标签（含特殊标注），class=glyphicon glyphicon-remove form-control-feedback#}
                <div class="input-group" id="email_check">
                    <div class="input-group-addon">邮箱</div>
                    <input type="text" class="form-control" id="username" placeholder="用户注册邮箱"
                           name="username" autocomplete="off">
{#                     <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>#}
                    <span class="" aria-hidden="true" id="email_check02"></span>
                </div>
                <div id="error_username"></div>
                <div class="input-group" id="password_check">
                    <div class="input-group-addon">密码</div>
                    <input type="password" class="form-control" id="password" placeholder="用户注册密码" name="password"
                           autocomplete="off">
                    <span class="" aria-hidden="true" id="password_check02"></span>
                </div>
                <div class="input-group" id="password_again_check">
                    <div class="input-group-addon">再次确认密码</div>
                    <input type="password" class="form-control" id="password_again" placeholder="再次确认密码"
                           autocomplete="off">
                    <span class="" aria-hidden="true" id="password_again_check02"></span>
                </div>
                <div class="input-group" id="name_check">
                    <div class="input-group-addon">用户昵称</div>
                    <input type="text" class="form-control" id="name" placeholder="注册用户昵称" name="name"
                           autocomplete="off">
                    <span class="" aria-hidden="true" id="name_check02"></span>
                </div>
            </div>

            <input type="submit" class="btn btn-primary" value="注册用户" style="width: 80%">

        </form>

{#        <div class="form-group has-success has-feedback">#}
{#            <label class="control-label" for="inputSuccess2">Input with success</label>#}
{#            <input type="text" class="form-control" id="inputSuccess2" aria-describedby="inputSuccess2Status">#}
{#            <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>#}
{#            <span id="inputSuccess2Status" class="sr-only">(success)</span>#}
{#        </div>#}
{#        <div class="form-group has-warning has-feedback">#}
{#            <label class="control-label" for="inputWarning2">Input with warning</label>#}
{#            <input type="text" class="form-control" id="inputWarning2" aria-describedby="inputWarning2Status">#}
{#            <span class="glyphicon glyphicon-warning-sign form-control-feedback" aria-hidden="true"></span>#}
{#            <span id="inputWarning2Status" class="sr-only">(warning)</span>#}
{#        </div>#}
{#        <div class="form-group has-error has-feedback">#}
{#            <label class="control-label" for="inputError2">Input with error</label>#}
{#            <input type="text" class="form-control" id="inputError2" aria-describedby="inputError2Status">#}
{#            <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>#}
{#            <span id="inputError2Status" class="sr-only">(error)</span>#}
{#        </div>#}
{#        <div class="form-group has-success has-feedback">#}
{#            <label class="control-label" for="inputGroupSuccess1">Input group with success</label>#}
{#            <div class="input-group">#}
{#                <span class="input-group-addon">@</span>#}
{#                <input type="text" class="form-control" id="inputGroupSuccess1"#}
{#                       aria-describedby="inputGroupSuccess1Status">#}
{#            </div>#}
{#            <span class="glyphicon glyphicon-ok form-control-feedback" aria-hidden="true"></span>#}
{#            <span id="inputGroupSuccess1Status" class="sr-only">(success)</span>#}
{#        </div>#}
    </div>
{% endblock %}